# https://github.com/realm/SwiftLint/blob/master/Rules.md

whitelist_rules:
- attributes
- class_delegate_protocol
- closing_brace
- closure_parameter_position
- closure_spacing
- colon
- comma
- compiler_protocol_init
- control_statement
- discouraged_direct_init
- empty_count
- empty_parameters
- empty_parentheses_with_trailing_closure
# - explicit_type_interface
- for_where
# - force_cast
# force_try
- generic_type_name
- implicit_getter
- is_disjoint
# - leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_nsgeometry_functions
- let_var_whitespace
- mark
- multiple_closures_with_trailing_closure
- nesting
# - no_grouping_extension
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- private_unit_test
- protocol_property_accessors_order
- redundant_discardable_let
- redundant_string_enum_value
- redundant_void_return
- return_arrow_whitespace
- shorthand_operator
- statement_position
- superfluous_disable_command
- switch_case_alignment
- syntactic_sugar
# - todo
- trailing_comma
- trailing_newline
- trailing_semicolon
- unneeded_break_in_switch
- unused_enumerated
- unused_optional_binding
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_whitespace
- void_return
- weak_delegate
- xctfail_message

included: # paths to include during linting. `--path` is ignored if present.
- Plock

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
